module.exports = function() {
  console.log('Hi');
  const temp = "hi";
  console.log(temp);
  const temp2 = "hi";
  console.log(temp2);
  const temp3 = "hi";
  console.log(temp3);
  const temp4 = "hi";
  console.log(temp4);
  const temp5 = "hi";
  console.log(temp5);
  const temp6 = "hi";
  console.log(temp6);
  const temp9 = "hi";
  console.log(temp9);
  const temp10 = "hi";
  console.log(temp10);
  const temp13 = "hi";
  console.log(temp13);
  const temp15 = "hi";
  console.log(temp15);
};